In [1]:
import torch

In [6]:
# self.expand_as(other.size())
other = torch.Tensor([0,0,0,0,0])
x = torch.Tensor([[1] ,[2],[3],[4],[5]])

In [7]:
x.expand_as(other)

RuntimeError: expand(torch.FloatTensor{[5, 1]}, size=[5]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

In [26]:
x = torch.Tensor([[1],[2],[3],[4]])
x.expand_as(torch.zeros(4,8))
# torch.zeros(1).expand_as(torch.zeros(8))

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])

In [23]:
!conda install tdqm

# from tdqm import trange
# tdqm.trange(10)

Solving environment: ...working... failed



PackagesNotFoundError: The following packages are not available from current channels:

  - tdqm

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.




In [35]:
x = torch.Tensor([[1,2,3], [1,2,3]])
display(x.repeat(1,2).view(4, -1))
display(x.repeat(1,2))

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

tensor([[1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.]])

In [51]:
n = 10
out = 5
import torch.nn.functional as F
x = torch.zeros(n, 3, out) # 10,3,5
y = F.softmax(x, dim=0)
y.size()

torch.Size([10, 3, 5])

SyntaxError: invalid syntax (<ipython-input-62-ee8a34e46716>, line 1)

In [57]:
torch.zeros(10)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [73]:
n = 2
out = 5
x = range(n*out) 
# h = torch.zeros(n,out)
h = torch.Tensor(x).view(2,5)
display(h.repeat(1,n).view(n*n, -1))
# display(h.repeat(1,n).size())
display(h.repeat(n,1))

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [5., 6., 7., 8., 9.]])

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [77]:
h = torch.zeros(5,2)
# h.repeat(1,3).size()
-9e15* torch.ones_like(h)

tensor([[-9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15]])

In [74]:
torch.empty

-9000000000000000.0